### ISSUE TITLE
Double-check secrets.SSH_KEY?

### ISSUE THREAD

**Issue by christopher-dG** [tkf/Baselet.jl#11]
Looks like your SSH key for TagBot is not working nicely: [link](https://github.com/tkf/Baselet.jl/runs/517986617?check_suite_focus=true#step:3:38) (found in https://github.com/JuliaRegistries/TagBot/issues/129)

**Comment by tkf** [comment]
Thanks for the ping! I don't know what went wrong but I just reset the SSH key. It looks like it's working now: https://github.com/tkf/Baselet.jl/runs/518123172?check_suite_focus=true#step:3:35
